services:
  app:
    build: .
    container_name: english-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/englishforit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    networks:
      - english-net

  db:
    image: pgvector/pgvector:pg15
    container_name: english-db
    environment:
      - POSTGRES_DB=englishforit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - english-net

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - english-net

volumes:
  db-data:


networks:
  english-net:
