spring.application.name=english-for-it-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/englishforit
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate

# OpenAI / OpenRouter
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.options.model=openai/gpt-oss-20b:free

# Vector Store Configuration
spring.ai.vectorstore.pgvector.index-type=HNSW
# Mail Configuration (MailDev)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
