spring.application.name=english-for-it-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/englishforit
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate

# OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}

# Security
rsa.public-key=classpath:certs/public.pem
rsa.private-key=classpath:certs/private.pem
